name: Build and Test SPFx Solution

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.19.1]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install global dependencies
      run: |
        npm install -g gulp-cli@2.3.0
        npm install -g @microsoft/generator-sharepoint@1.16.1
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint (non-blocking)
      run: npx eslint src/ --ext .ts,.tsx --format compact || echo "ESLint completed with warnings/errors"
      
    - name: Build solution
      run: |
        gulp build
        gulp bundle --ship
        gulp package-solution --ship
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: spfx-package-node-${{ matrix.node-version }}
        path: |
          sharepoint/solution/*.sppkg
          
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-node-${{ matrix.node-version }}
        path: |
          lib/
          dist/
          temp/manifests.json
          
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16.19.1'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint with detailed output
      run: npx eslint src/ --ext .ts,.tsx --format json --output-file eslint-results.json || true
      
    - name: Upload ESLint results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: eslint-results
        path: eslint-results.json
